version: "3"
services:
  voting_nginx:
    ports:
      - "8003:80"
    build: ./nginx
    volumes:
      - ./app/www:/usr/share/nginx/html/
    depends_on:
      - voting_gunicorn
  voting_gunicorn:
    build: ./gunicorn
    volumes:
      - ./app:/app