version: "3.3"
services:
  nginx:
    build: ./nginx
    volumes:
      - ./app/www:/usr/share/nginx/html/
    ports:
      - "80:80"
    depends_on:
      - gunicorn
  gunicorn:
    build: ./gunicorn
    volumes:
      - ./app:/app
