version: '2.2'
services:
  voting-backend:
    build: .
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:9::2
  voting-frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - voting-backend
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:9::1
networks:
  checkernet:
    external: true
