
version: '3.6'
services:
  voting-backend:
    build: .
    image: dockerreg.enowars.com:5000/voting-backend
    networks:
     - bridge
     - enoverlay
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=voting-db
     - MONGO_PORT=27017
     - MONGO_USER=ipv6islove
     - MONGO_PASSWORD=dockerislove
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=voting-checker"
        - "traefik.docker.network=enoverlay"
        - "traefik.frontend.rule=Host:voting.checker.enowars.com,service9.checker.enowars.com,f07e.checker.enowars.com"
        - "traefik.port=3031"
      replicas: 1
  voting-db:
    image: mongo
    networks:
      - enoverlay
    volumes:
      - voting_db_data:/data/db
#we need to fix the node otherwise the volumes are lost after migration :/
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==blade5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove


networks:
  bridge:
    external: true
  enoverlay:
    external: true
volumes:
  voting_db_data:
