version: '3.6'

services:
  voting-backend:
    build: .
    ports:
      - 8003:3031
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=voting-db
     - MONGO_PORT=27017
     - MONGO_USER=ipv6islove
     - MONGO_PASSWORD=dockerislove
  voting-db:
    image: mongo
    volumes:
      - ./voting_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove